import numpy as np, matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
n = np.array([2,4,6,8,9,10])
out = np.array([8.6e-4,2.5e-4,6.5e-5,2.1e-5,7.6e-6,3.6e-6])
cot = np.array([1.774e-2,2.984e-2,3.891e-2,3.961e-2,4.220e-2,4.269e-2])
BLUE, ORANGE = "#0a7fad", "#c8680a"
fig, ax = plt.subplots(figsize=(5.2,2.6))
ax.set_facecolor("#eaeaf2"); ax.grid(color="white", lw=1); ax.set_axisbelow(True)
for s in ax.spines.values(): s.set_visible(False)
ax.plot(n, cot, "-o", color=BLUE, lw=2, ms=6, label="chain-of-thought")
ax.plot(n, out, "-s", color=ORANGE, lw=2, ms=6, label="outcome (answer-dependent)")
nn = np.linspace(2,10,50)
ax.plot(nn, out[0]*0.5**(nn-2), ":", color="0.35", lw=1.5, label=r"$\lambda^{n}$, $\lambda=0.5$")
ax.set_yscale("log"); ax.set_xlabel("letters $n$"); ax.set_ylabel(r"gradient norm at $\theta_0$")
ax.set_xticks(n)
ax.text(10.15, cot[-1], "CoT", color="0.15", va="center", fontsize=9)
ax.text(10.15, out[-1], "outcome", color="0.15", va="center", fontsize=9)
ax.set_xlim(1.6, 11.4)
ax.legend(frameon=True, fontsize=8, loc="lower left")
fig.tight_layout()
for ext in ("pdf","png"): fig.savefig(f"Paper/figures/damping_decay.{ext}", dpi=200)
